### ISSUE TITLE
Requirements fails to install

### ISSUE THREAD

**Issue by l0ris** [FINRAOS/yum-nginx-api#5]
Tried on fresh Centos 7.2 install, the installation of requirements fails with the message: 
"Could not find a version that satisfies the requirement requirements.txt (from versions: )
No matching distribution found for requirements.txt"

**Comment by marshyski** [comment]
@l0ris this most recent merge, should've fixed the problem.  Mind testing it?

**Comment by marshyski** [comment]
@l0ris rewrote project in Go. Published the binary under releases and new docker image is published.  Closing issue.
